### ISSUE TITLE
Rename organization to avoid confusion with the official ros2 java bindings

### ISSUE THREAD

**Issue by esteve** [ros2java-alfred/ros2_java#3]
Since the organization description already states that these bindings are a fork and not official, and are incompatible with the official ROS2 Java bindings, it'd be helpful to rename the organization to avoid confusing users. I think `ros2java_alfred` would be a good name.

Thanks!

**Comment by Theosakamg** [comment]
Transfered to ros2java-alfred

**Comment by esteve** [comment]
@Theosakamg thank you very much! I see that https://github.com/ros2java still exists, but is empty. Do you plan to use it? Could you remove it or transfer it to me? Thanks!

**Comment by esteve** [comment]
@Theosakamg thanks for adding me to the organization. Would you mind adding me owner rights so I can change the description? Thanks.

**Comment by esteve** [comment]
@Theosakamg I'd also need owner access in GitHub for Travis, could you add me as an owner to the ros2java organization?

**Comment by Theosakamg** [comment]
I plan to use it for final official ROS2java implementation.
You are now co-owner..

**Comment by esteve** [comment]
Merci beaucoup! :-)

**Comment by esteve** [comment]
@Theosakamg @elehuitouze I'm going to enable 2FA to `ros2java`, I think GitHub may revoke your access, so please enable 2FA as soon as possible and I'll add you again. For more info:

https://help.github.com/articles/about-two-factor-authentication/
https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/

**Comment by Theosakamg** [comment]
enabled

**Comment by Theosakamg** [comment]
@esteve can you change my role to owner, Thank
