### ISSUE TITLE
Rename project on readthedocs

### ISSUE THREAD

**Issue by esteve** [ros2java-alfred/ros2_java#5]
I was about to register a readthedocs subproject for https://github.com/ros2-java and it turns out you already did it, but it points to this repository. Could you rename the readthedocs ros2-java project to ros2java-alfred?

Thanks!

**Comment by Theosakamg** [comment]
Sorry I just click to import from Gihub but opposite to travis. Readthedocs auto-create the project name (based on Github repository) but without ros2java-alfred workspace.
Now I rename to ros2java_alfred but he doesn't change the page....
I think more simple is to provide to me your Readthedocs username for make a transfert.

**Comment by esteve** [comment]
My username on readthedocs is "esteve". Thanks.

**Comment by Theosakamg** [comment]
I have not found the transfer function. So I completely remove the readthedocs repository

**Comment by esteve** [comment]
Thanks!
